apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
spec:
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wordpress
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.mariadb.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  clusterIP: None
