apiVersion: v2
name: wordpress
description: Managed WordPress with MariaDB — deployed by K8s Hosting Platform
version: 1.0.0
appVersion: "6.x"
type: application
keywords:
  - wordpress
  - cms
  - php
  - blog
home: https://wordpress.org
sources:
  - https://github.com/phoenixtechnam/hosting-platform-application-catalog
